<?php

use App\Http\Controllers\Admin\AboutContentController;
use App\Http\Controllers\Admin\BillingController;
use App\Http\Controllers\Admin\CaseController;
use App\Http\Controllers\Admin\ClientController;
use App\Http\Controllers\Admin\IndustryCrudController;
use App\Http\Controllers\Admin\InsightCrudController;
use App\Http\Controllers\Admin\ReportController;
use App\Http\Controllers\Admin\ServiceCrudController;
use App\Http\Controllers\Admin\SettingsController;
use App\Http\Controllers\Admin\TeamController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\WebsiteContentController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\SiteController;
use Illuminate\Support\Facades\Route;

Route::get('/', [SiteController::class, 'home'])->name('home');
Route::get('/about', [SiteController::class, 'about'])->name('about');
Route::get('/services', [SiteController::class, 'services'])->name('services');
Route::get('/capabilities/{slug}', [SiteController::class, 'capabilityShow'])->name('capabilities.show');
Route::get('/industries', [SiteController::class, 'industries'])->name('industries');
Route::get('/insights', [SiteController::class, 'insights'])->name('insights');
Route::get('/insights/{slug}', [SiteController::class, 'insightShow'])->name('insights.show');
Route::get('/team/{slug}', [SiteController::class, 'teamShow'])->name('team.show');
Route::get('/contact', [SiteController::class, 'contact'])->name('contact');
Route::get('/privacy-policy', [SiteController::class, 'privacy'])->name('privacy');
Route::get('/terms-and-conditions', [SiteController::class, 'terms'])->name('terms');
Route::get('/compliance', [SiteController::class, 'compliance'])->name('compliance');
Route::post('/contact', [ContactController::class, 'store'])->name('contact.store');

Route::prefix('admin')->name('admin.')->group(function (): void {
    Route::view('/', 'admin.dashboard')->name('dashboard');
    Route::get('/website-content', [WebsiteContentController::class, 'index'])->name('website-content');
    Route::get('/website-content/create', [WebsiteContentController::class, 'create'])->name('website-content.create');
    Route::post('/website-content', [WebsiteContentController::class, 'store'])->name('website-content.store');
    Route::get('/website-content/{id}/edit', [WebsiteContentController::class, 'edit'])->name('website-content.edit');
    Route::patch('/website-content/{id}', [WebsiteContentController::class, 'update'])->name('website-content.update');
    Route::get('/website-content/{id}/delete', [WebsiteContentController::class, 'deleteConfirm'])->name('website-content.delete-confirm');
    Route::delete('/website-content/{id}', [WebsiteContentController::class, 'destroy'])->name('website-content.destroy');
    Route::get('/about-content', [AboutContentController::class, 'edit'])->name('about-content.edit');
    Route::post('/about-content', [AboutContentController::class, 'update'])->name('about-content.update');
    Route::get('/services', [ServiceCrudController::class, 'index'])->name('services.index');
    Route::get('/services/create', [ServiceCrudController::class, 'create'])->name('services.create');
    Route::post('/services', [ServiceCrudController::class, 'store'])->name('services.store');
    Route::get('/services/{id}/edit', [ServiceCrudController::class, 'edit'])->name('services.edit');
    Route::patch('/services/{id}', [ServiceCrudController::class, 'update'])->name('services.update');
    Route::get('/services/{id}/delete', [ServiceCrudController::class, 'deleteConfirm'])->name('services.delete-confirm');
    Route::delete('/services/{id}', [ServiceCrudController::class, 'destroy'])->name('services.destroy');

    Route::get('/industries', [IndustryCrudController::class, 'index'])->name('industries.index');
    Route::get('/industries/create', [IndustryCrudController::class, 'create'])->name('industries.create');
    Route::post('/industries', [IndustryCrudController::class, 'store'])->name('industries.store');
    Route::get('/industries/{id}/edit', [IndustryCrudController::class, 'edit'])->name('industries.edit');
    Route::patch('/industries/{id}', [IndustryCrudController::class, 'update'])->name('industries.update');
    Route::get('/industries/{id}/delete', [IndustryCrudController::class, 'deleteConfirm'])->name('industries.delete-confirm');
    Route::delete('/industries/{id}', [IndustryCrudController::class, 'destroy'])->name('industries.destroy');

    Route::get('/insights', [InsightCrudController::class, 'index'])->name('insights.index');
    Route::get('/insights/create', [InsightCrudController::class, 'create'])->name('insights.create');
    Route::post('/insights', [InsightCrudController::class, 'store'])->name('insights.store');
    Route::get('/insights/{id}/edit', [InsightCrudController::class, 'edit'])->name('insights.edit');
    Route::patch('/insights/{id}', [InsightCrudController::class, 'update'])->name('insights.update');
    Route::get('/insights/{id}/delete', [InsightCrudController::class, 'deleteConfirm'])->name('insights.delete-confirm');
    Route::delete('/insights/{id}', [InsightCrudController::class, 'destroy'])->name('insights.destroy');

    Route::get('/team', [TeamController::class, 'index'])->name('team');
    Route::get('/team/create', [TeamController::class, 'create'])->name('team.create');
    Route::post('/team', [TeamController::class, 'store'])->name('team.store');
    Route::get('/team/{slug}/edit', [TeamController::class, 'edit'])->where('slug', '[a-z0-9\-]+')->name('team.edit');
    Route::patch('/team/{slug}', [TeamController::class, 'update'])->where('slug', '[a-z0-9\-]+')->name('team.update');
    Route::get('/team/{slug}/delete', [TeamController::class, 'deleteConfirm'])->where('slug', '[a-z0-9\-]+')->name('team.delete-confirm');
    Route::delete('/team/{slug}', [TeamController::class, 'destroy'])->where('slug', '[a-z0-9\-]+')->name('team.destroy');
    Route::get('/clients', [ClientController::class, 'index'])->name('clients');
    Route::get('/clients/create', [ClientController::class, 'create'])->name('clients.create');
    Route::post('/clients', [ClientController::class, 'store'])->name('clients.store');
    Route::get('/clients/{id}', [ClientController::class, 'show'])->name('clients.show')->whereNumber('id');
    Route::get('/clients/{id}/edit', [ClientController::class, 'edit'])->name('clients.edit')->whereNumber('id');
    Route::patch('/clients/{id}', [ClientController::class, 'update'])->name('clients.update')->whereNumber('id');
    Route::get('/clients/{id}/delete', [ClientController::class, 'deleteConfirm'])->name('clients.delete-confirm')->whereNumber('id');
    Route::delete('/clients/{id}', [ClientController::class, 'destroy'])->name('clients.destroy')->whereNumber('id');
    Route::get('/cases', [CaseController::class, 'index'])->name('cases');
    Route::get('/cases/create', [CaseController::class, 'create'])->name('cases.create');
    Route::post('/cases', [CaseController::class, 'store'])->name('cases.store');
    Route::get('/cases/{id}', [CaseController::class, 'show'])->name('cases.show');
    Route::get('/cases/{id}/edit', [CaseController::class, 'edit'])->name('cases.edit');
    Route::patch('/cases/{id}', [CaseController::class, 'update'])->name('cases.update');
    Route::post('/cases/{id}/notes', [CaseController::class, 'addNote'])->name('cases.add-note');
    Route::post('/cases/{id}/close', [CaseController::class, 'close'])->name('cases.close');
    Route::get('/cases/{id}/delete', [CaseController::class, 'deleteConfirm'])->name('cases.delete-confirm');
    Route::delete('/cases/{id}', [CaseController::class, 'destroy'])->name('cases.destroy');
    Route::get('/billing', [BillingController::class, 'index'])->name('billing');
    /* Legacy "Receipts" module merged into payment receipts */
    Route::redirect('billing/receipts', 'billing/payments', 301);
    Route::redirect('billing/receipts/create', 'billing/payments/create', 301);
    Route::get('/billing/{module}', [BillingController::class, 'moduleIndex'])->name('billing.module.index');
    Route::get('/billing/{module}/create', [BillingController::class, 'create'])->name('billing.module.create');
    Route::post('/billing/{module}', [BillingController::class, 'store'])->name('billing.module.store');
    Route::get('/billing/{module}/{id}/preview/pdf', [BillingController::class, 'downloadPreviewPdf'])->name('billing.module.preview.pdf');
    Route::get('/billing/{module}/{id}/preview/print', [BillingController::class, 'printPreview'])->name('billing.module.preview.print');
    Route::get('/billing/{module}/{id}/preview', [BillingController::class, 'preview'])->name('billing.module.preview');
    Route::get('/billing/{module}/{id}/edit', [BillingController::class, 'edit'])->name('billing.module.edit');
    Route::patch('/billing/{module}/{id}', [BillingController::class, 'update'])->name('billing.module.update');
    Route::get('/reports', [ReportController::class, 'index'])->name('reports');
    Route::get('/reports/export', [ReportController::class, 'export'])->name('reports.export');
    Route::get('/users', [UserController::class, 'index'])->name('users');
    Route::get('/users/{id}', [UserController::class, 'show'])->name('users.show');
    Route::post('/users/{id}/toggle-status', [UserController::class, 'toggleStatus'])->name('users.toggle-status');
    Route::post('/users/{id}/reset-password', [UserController::class, 'resetPassword'])->name('users.reset-password');
    Route::get('/users/{id}/edit', [UserController::class, 'edit'])->name('users.edit');
    Route::patch('/users/{id}', [UserController::class, 'update'])->name('users.update');
    Route::get('/users/{id}/delete', [UserController::class, 'deleteConfirm'])->name('users.delete-confirm');
    Route::delete('/users/{id}', [UserController::class, 'destroy'])->name('users.destroy');
    Route::view('/profile', 'admin.profile')->name('profile');
    Route::view('/account-settings', 'admin.account-settings')->name('account-settings');
    Route::view('/change-password', 'admin.change-password')->name('change-password');
    Route::get('/settings', [SettingsController::class, 'index'])->name('settings');
    Route::post('/settings', [SettingsController::class, 'update'])->name('settings.update');
});
